import Head from 'next/head';
import Layout from '../components/Layout/Layout';
import Modal from '../components/Modal/Modal';
import 'react-datepicker/dist/react-datepicker.css';
import { useSelector } from 'react-redux';
import SideBar from '../components/SideBar/SideBar';
import Column from '../components/Column/Column';
import ModalDetaile from '../components/ModalDetaile/ModalDetaile';

export default function Home() {
  const { modalShow, tasks, info_modal_show } = useSelector(
    (state) => state.task
  );
  const new_tasks = tasks.filter((task) => task.position == 'new');
  const progress_tasks = tasks.filter((task) => task.position == 'progress');
  const done_tasks = tasks.filter((task) => task.position == 'done');

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="page container">
          
          <div className="sidebar">
            <SideBar />
          </div>
          <div className="columns">
            <Column position="new" inner_tasks={new_tasks} />
            <Column position="progress" inner_tasks={progress_tasks} />
            <Column position="done" inner_tasks={done_tasks} />
          </div>
        </div>

        {modalShow && <Modal />}
        {info_modal_show && <ModalDetaile />}
      </Layout>
    </div>
  );
}
